FROM python:3.8-slim-buster 
WORKDIR /Facial_Expression_Identification
COPY requirements.txt .
RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install -r requirements.txt  
COPY . .
# Make port 5000 available to the world outside this container
ENV FLASK_ENV production
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD ["backend/backend.py" ]