FROM node:14.17.0-alpine AS base
# Set the working directory to /app
WORKDIR /Facial_Expression_Identification
COPY package*.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1 -g --silent
COPY . .

CMD ["npm", "start"]
